#
#  @Author: German Cano Quiveu, germancq@gmail.com 
#  @Date: 2019-09-21 22:19:47 
#  @Last Modified by: German Cano Quiveu, germancq@gmail.com
#  @Last Modified time: 2019-09-21 22:21:14
# 

VERILOG_SOURCES = ../../lookuptable.sv 

TOPLEVEL=lookup_table
MODULE=lookuptable_test
include $(COCOTB)/makefiles/Makefile.inc
include $(COCOTB)/makefiles/Makefile.sim


clean_results : 
	rm *.pyc
	rm *.xml
